//
// Created by root on 11/8/17.
//

#ifndef DYNAMIC_SYSTEMS_DSL_TRANSLATOR_TYPE_H
#define DYNAMIC_SYSTEMS_DSL_TRANSLATOR_TYPE_H


enum Type {
    DOUBLE, TABLE, STRING, DERIVATIVE, VOID
};


#endif //DYNAMIC_SYSTEMS_DSL_TRANSLATOR_TYPE_H
